"""Read-only Futures Screener presentation metadata.

Separates broad 15m discovery rows from frozen COMBO_02 v1 watcher state.
Does not open paper trades, emit Telegram, or alter strategy engines.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Mapping

import structlog

from app.research.v1_production import V1_SYMBOLS, normalize_symbol
from app.services.paper_classification import STRATEGY_COMBO_02_V1
from app.services.v1_paper_watcher import is_v1_long_entry

logger = structlog.get_logger(__name__)

# API status codes (fail-closed)
STATUS_DISCOVERY_ONLY = "DISCOVERY_ONLY"
STATUS_V1_WAITING_NO_BOS = "V1_WAITING_NO_BOS"
STATUS_V1_BLOCKED_HTF = "V1_BLOCKED_HTF"
STATUS_V1_BLOCKED_1H = "V1_BLOCKED_1H_TREND"
STATUS_V1_BLOCKED_4H = "V1_BLOCKED_4H_TREND"
STATUS_V1_BLOCKED_OPEN = "V1_BLOCKED_OPEN_POSITION"
STATUS_V1_ELIGIBLE = "V1_ELIGIBLE"
STATUS_V1_PAPER_OPEN = "V1_PAPER_OPEN"
STATUS_V1_DATA_UNAVAILABLE = "V1_DATA_UNAVAILABLE"

POTENTIAL_LEVELS_TOOLTIP = (
    "Reference levels generated by the general screener. "
    "They are not active orders, not paper positions, and not Telegram eligible. "
    "They may exist before setup confirmation."
)

SCREEN_STATE_LEGEND = {
    "NEUTRAL": "No actionable screen direction; not a trade instruction",
    "BULLISH_LOCAL_TREND": "Local structure is bullish; not necessarily a v1 entry",
    "BEARISH_LOCAL_TREND": "Local structure is bearish; long v1 entry is blocked",
    "WAITING": "Setup has not completed / no confirmed entry",
    "CONFLICT": "Screener conditions disagree; no valid screen setup",
    "DISCOVERY_ONLY": "Broad screener observation; excluded from frozen v1",
    "V1_ELIGIBLE": "Separate 1h/4h COMBO_02 v1 watcher has confirmed a valid entry",
    "V1_PAPER_OPEN": "A persisted v1 paper trade already exists",
}


def _fv_value(row: Mapping[str, Any], key: str) -> Any:
    raw = row.get(key)
    if isinstance(raw, Mapping):
        return raw.get("value")
    return raw


def _as_float(value: Any) -> float | None:
    if value is None:
        return None
    try:
        n = float(value)
    except (TypeError, ValueError):
        return None
    if not (n == n):  # NaN
        return None
    return n


def screen_setup_unconfirmed(setup: Any) -> bool:
    s = str(setup or "").upper().strip()
    return s in ("", "WAITING", "CONFLICT", "NO_SETUP")


def build_potential_levels(row: Mapping[str, Any]) -> dict[str, Any]:
    """Presentation-only potential levels from screener setup fields."""
    setup = str(_fv_value(row, "setup_signal") or "").upper()
    entry = _as_float(_fv_value(row, "setup_entry"))
    stop = _as_float(_fv_value(row, "setup_sl"))
    tp1 = _as_float(_fv_value(row, "setup_tp1"))
    rr = _as_float(_fv_value(row, "setup_rr"))
    confirmed = entry is not None and setup not in (
        "",
        "WAITING",
        "CONFLICT",
        "NO_SETUP",
    )
    reference_only = screen_setup_unconfirmed(setup) or not confirmed
    return {
        "entry": entry,
        "stop": stop,
        "tp1": tp1,
        "rr": rr,
        "is_confirmed": bool(confirmed),
        "reference_only": bool(reference_only),
        "display_mode": "candidate" if reference_only else "potential",
        "tooltip": POTENTIAL_LEVELS_TOOLTIP
        + (
            " Reference only — setup not confirmed."
            if reference_only
            else ""
        ),
    }


def _bos_status_from_eval(eval_result: Mapping[str, Any] | None) -> str:
    if not eval_result:
        return "NONE"
    gates = eval_result.get("gates") or {}
    if bool(gates.get("bos")):
        direction = str(eval_result.get("direction") or "").upper()
        if direction == "LONG":
            return "BULLISH_BOS"
        if direction == "SHORT":
            return "BEARISH_BOS"
        return "BOS"
    status = str(eval_result.get("status") or "").upper()
    if "BOS" in status:
        return status
    return "NONE"


def classify_v1_status(
    *,
    symbol: str,
    snapshot: Mapping[str, Any] | None,
    open_trade_id: str | None = None,
    book: Mapping[str, Any] | None = None,
) -> dict[str, Any]:
    """Map cached watcher snapshot → fail-closed v1_status (never from 15m)."""
    sym = normalize_symbol(symbol)
    if sym not in V1_SYMBOLS:
        return {
            "in_v1_universe": False,
            "status": STATUS_DISCOVERY_ONLY,
            "label": "DISCOVERY ONLY",
            "tier": None,
            "timeframe": None,
            "trend_1h": None,
            "trend_4h": None,
            "htf_alignment": None,
            "bos_status": None,
            "open_trade_id": None,
            "last_evaluated_at_utc": None,
            "tooltip": (
                "This symbol is not in the frozen COMBO_02 v1 paper/live universe. "
                "Screener observations cannot create v1 paper trades or Telegram alerts."
            ),
        }

    tier = None
    risk_percent = None
    if book:
        tier = book.get("tier")
        risk_percent = book.get("risk_percent")

    base: dict[str, Any] = {
        "in_v1_universe": True,
        "tier": tier,
        "risk_percent": risk_percent,
        "timeframe": "1h",
        "trend_1h": None,
        "trend_4h": None,
        "htf_alignment": None,
        "bos_status": "NONE",
        "open_trade_id": open_trade_id,
        "last_evaluated_at_utc": None,
        "eval_status": None,
    }

    if open_trade_id:
        base.update(
            {
                "status": STATUS_V1_PAPER_OPEN,
                "label": f"V1 PAPER OPEN — trade_id {open_trade_id}",
                "tooltip": "A persisted COMBO_02 v1 paper trade already exists for this symbol.",
            }
        )
        # Still attach snapshot fields when present for the watcher panel.
        if snapshot:
            eval_result = snapshot.get("eval") if isinstance(snapshot.get("eval"), Mapping) else snapshot
            htf = (eval_result or {}).get("htf") or {}
            base["trend_1h"] = htf.get("trend_1h")
            base["trend_4h"] = htf.get("trend_4h")
            base["htf_alignment"] = htf.get("htf_alignment")
            base["bos_status"] = _bos_status_from_eval(eval_result)  # type: ignore[arg-type]
            base["last_evaluated_at_utc"] = snapshot.get("evaluated_at_utc")
            base["eval_status"] = (eval_result or {}).get("status")
        return base

    if not snapshot:
        base.update(
            {
                "status": STATUS_V1_DATA_UNAVAILABLE,
                "label": "V1 DATA UNAVAILABLE",
                "tooltip": (
                    "No cached COMBO_02 v1 watcher evaluation snapshot. "
                    "Eligibility is never inferred from the 15m screener row."
                ),
            }
        )
        return base

    eval_result = snapshot.get("eval") if isinstance(snapshot.get("eval"), Mapping) else None
    if eval_result is None and any(
        k in snapshot for k in ("status", "htf", "gates", "trend_1h")
    ):
        eval_result = snapshot  # already flattened

    if not isinstance(eval_result, Mapping):
        base["last_evaluated_at_utc"] = snapshot.get("evaluated_at_utc")
        base.update(
            {
                "status": STATUS_V1_DATA_UNAVAILABLE,
                "label": "V1 DATA UNAVAILABLE",
                "tooltip": "Watcher snapshot present but missing evaluation payload.",
            }
        )
        return base

    reason = str(eval_result.get("reason") or "").lower()
    if reason in ("missing_1h", "missing_4h", "insufficient_1h_history"):
        base["last_evaluated_at_utc"] = snapshot.get("evaluated_at_utc")
        base["tip_bar"] = snapshot.get("tip_bar")
        base["eval_status"] = eval_result.get("status")
        base.update(
            {
                "status": STATUS_V1_DATA_UNAVAILABLE,
                "label": "V1 DATA UNAVAILABLE",
                "tooltip": f"Watcher cannot evaluate tip ({reason}).",
            }
        )
        return base

    htf = eval_result.get("htf") or {}
    trend_1h = str(htf.get("trend_1h") or snapshot.get("trend_1h") or "").upper() or None
    trend_4h = str(htf.get("trend_4h") or snapshot.get("trend_4h") or "").upper() or None
    htf_alignment = (
        str(htf.get("htf_alignment") or snapshot.get("htf_alignment") or "").upper()
        or None
    )
    bos_status = _bos_status_from_eval(eval_result)
    base.update(
        {
            "trend_1h": trend_1h,
            "trend_4h": trend_4h,
            "htf_alignment": htf_alignment,
            "bos_status": bos_status,
            "last_evaluated_at_utc": snapshot.get("evaluated_at_utc"),
            "eval_status": eval_result.get("status"),
            "tip_bar": snapshot.get("tip_bar"),
        }
    )

    # Never mark ELIGIBLE from anything except the combo evaluator snapshot.
    if is_v1_long_entry(eval_result):
        base.update(
            {
                "status": STATUS_V1_ELIGIBLE,
                "label": "V1 ELIGIBLE — confirmed 1h entry",
                "tooltip": (
                    "Read-only: COMBO_02 v1 watcher snapshot reports a confirmed "
                    "1h LONG_ENTRY_CANDIDATE. This does not create a trade from the UI."
                ),
            }
        )
        return base

    if htf_alignment and htf_alignment != "HTF_ALIGNED":
        base.update(
            {
                "status": STATUS_V1_BLOCKED_HTF,
                "label": "V1 BLOCKED — HTF not aligned",
                "tooltip": f"HTF alignment is {htf_alignment}, not HTF_ALIGNED.",
            }
        )
        return base

    if trend_4h and trend_4h != "BULLISH":
        base.update(
            {
                "status": STATUS_V1_BLOCKED_4H,
                "label": "V1 BLOCKED — 4h trend not bullish",
                "tooltip": f"4h trend is {trend_4h}.",
            }
        )
        return base

    if trend_1h and trend_1h != "BULLISH":
        base.update(
            {
                "status": STATUS_V1_BLOCKED_1H,
                "label": "V1 BLOCKED — 1h trend not bullish",
                "tooltip": f"1h trend is {trend_1h}.",
            }
        )
        return base

    gates = eval_result.get("gates") or {}
    if not bool(gates.get("bos")):
        base.update(
            {
                "status": STATUS_V1_WAITING_NO_BOS,
                "label": "V1 WAITING — no confirmed 1h BOS",
                "tooltip": "Waiting for a confirmed 1h BULLISH_BOS under COMBO_02.",
            }
        )
        return base

    # BOS present but other gates / RR / sticky skip — still not eligible.
    base.update(
        {
            "status": STATUS_V1_WAITING_NO_BOS,
            "label": "V1 WAITING — no confirmed 1h BOS",
            "tooltip": (
                str(eval_result.get("reason") or eval_result.get("status") or "")
                or "Watcher snapshot is not a confirmed v1 LONG entry."
            ),
        }
    )
    return base


def open_v1_trade_ids(paper_engine: Any | None) -> dict[str, str]:
    """symbol → trade id for open COMBO_02_V1 positions only."""
    out: dict[str, str] = {}
    if paper_engine is None:
        return out
    try:
        with getattr(paper_engine, "_lock", None) or _NullCtx():
            open_map = getattr(paper_engine, "_open", {}) or {}
            for sym, pos in list(open_map.items()):
                snip = getattr(pos, "signal_snippet", None) or {}
                if not isinstance(snip, dict):
                    snip = {}
                sid = str(snip.get("strategy_id") or "")
                if sid == STRATEGY_COMBO_02_V1:
                    out[normalize_symbol(sym)] = str(getattr(pos, "id", "") or "")
    except Exception:  # noqa: BLE001
        return out
    return out


class _NullCtx:
    def __enter__(self) -> "_NullCtx":
        return self

    def __exit__(self, *args: Any) -> None:
        return None


def enrich_screener_row_dict(
    row: Mapping[str, Any],
    *,
    screen_timeframe: str,
    v1_snapshots: Mapping[str, Mapping[str, Any]] | None = None,
    open_trades: Mapping[str, str] | None = None,
    v1_books: Mapping[str, Mapping[str, Any]] | None = None,
) -> dict[str, Any]:
    """Attach presentation metadata; never sets telegram eligibility true."""
    out = dict(row)
    sym = normalize_symbol(str(row.get("symbol") or ""))
    snaps = v1_snapshots or {}
    trades = open_trades or {}
    books = v1_books or {}

    local_trend = _fv_value(row, "setup_trend") or _fv_value(row, "market_structure") or _fv_value(
        row, "structure"
    )
    screen_signal = _fv_value(row, "market_signal")
    screen_setup = _fv_value(row, "setup_signal")

    v1_status = classify_v1_status(
        symbol=sym,
        snapshot=snaps.get(sym),
        open_trade_id=trades.get(sym),
        book=books.get(sym),
    )

    out["screen_timeframe"] = screen_timeframe
    out["local_trend"] = (
        str(local_trend).upper() if local_trend is not None else None
    )
    out["screen_signal"] = (
        str(screen_signal).upper() if screen_signal is not None else None
    )
    out["screen_setup"] = (
        str(screen_setup).upper() if screen_setup is not None else None
    )
    out["potential_levels"] = build_potential_levels(row)
    out["v1_status"] = v1_status
    out["is_telegram_eligible"] = False
    if trades.get(sym):
        out["v1_paper_trade"] = {
            "open": True,
            "trade_id": trades.get(sym),
            "label": "V1 paper trade open — view position",
            "href": "/paper",
        }
    else:
        out["v1_paper_trade"] = {"open": False, "trade_id": None}
    return out


def enrich_screener_payload(
    payload: dict[str, Any],
    *,
    screen_timeframe: str | None = None,
) -> dict[str, Any]:
    """Enrich a screener API/WS payload in place (presentation only)."""
    from app.services.v1_paper_watcher import get_v1_paper_watcher

    tf = screen_timeframe
    if not tf:
        try:
            from app.services.setup_signals import get_setup_signal_service

            tf = str(get_setup_signal_service().config.mtf_setup or "15m")
        except Exception:  # noqa: BLE001
            tf = "15m"

    snaps: dict[str, Mapping[str, Any]] = {}
    books: dict[str, Mapping[str, Any]] = {}
    open_trades: dict[str, str] = {}
    watcher: Any = None
    try:
        from app.research.v1_production import enabled_v1_books

        for book in enabled_v1_books():
            books[book.symbol] = {
                "symbol": book.symbol,
                "tier": book.tier,
                "risk_percent": book.risk_percent,
                "timeframe": book.timeframe,
            }
    except Exception:  # noqa: BLE001
        books = {s: {"symbol": s} for s in V1_SYMBOLS}
    try:
        watcher = get_v1_paper_watcher()
        # Cache only — never run evaluate_combination_at_bar on screener refresh.
        # Missing cache → V1 DATA UNAVAILABLE (fail closed). Snapshots are filled by
        # V1PaperWatcher.on_closed_1h and optionally /paper/status (TTL-gated).
        snaps = watcher.get_presentation_snapshots(refresh=False)
        for book in watcher.books:
            books[book.symbol] = {
                "symbol": book.symbol,
                "tier": book.tier,
                "risk_percent": book.risk_percent,
                "timeframe": book.timeframe,
            }
        try:
            from app.services.paper_trade import get_paper_trade_engine

            open_trades = open_v1_trade_ids(get_paper_trade_engine())
        except Exception:  # noqa: BLE001
            open_trades = {}
    except Exception as exc:  # noqa: BLE001
        logger.warning("screener_v1_watcher_enrich_failed", error=str(exc))
        snaps = {}
        open_trades = {}
    # Always emit BTC/ETH/SOL cards — never blank the panel on transient failures.
    watcher_view = build_v1_watcher_view(
        snaps=snaps,
        books=books,
        open_trades=open_trades,
        watcher=watcher,
    )
    rows = payload.get("rows") or []
    enriched = [
        enrich_screener_row_dict(
            r,
            screen_timeframe=tf,
            v1_snapshots=snaps,
            open_trades=open_trades,
            v1_books=books,
        )
        if isinstance(r, Mapping)
        else r
        for r in rows
    ]
    payload["rows"] = enriched
    payload["screen_timeframe"] = tf
    payload["screener_identity"] = {
        "title": "GENERAL MARKET SCREENER",
        "subtitle": (
            "Structure and setup discovery only. Not a COMBO_02 v1 trade signal."
        ),
        "screen_setup_timeframe": tf,
        "v1_execution": "1h setup + 4h/1h HTF alignment + confirmed BOS",
        "is_telegram_eligible": False,
        "legend": SCREEN_STATE_LEGEND,
    }
    payload["v1_watcher_view"] = watcher_view
    # Informational only — never true for generic screener.
    payload["is_telegram_eligible"] = False
    return payload


def build_v1_watcher_view(
    *,
    snaps: Mapping[str, Mapping[str, Any]],
    books: Mapping[str, Mapping[str, Any]],
    open_trades: Mapping[str, str],
    watcher: Any,
) -> list[dict[str, Any]]:
    """Read-only COMBO_02 v1 watcher panel rows (BTC/ETH/SOL only)."""
    rows: list[dict[str, Any]] = []
    for sym in sorted(V1_SYMBOLS):
        book = books.get(sym) or {}
        status = classify_v1_status(
            symbol=sym,
            snapshot=snaps.get(sym),
            open_trade_id=open_trades.get(sym),
            book=book,
        )
        tip = None
        last_eval = status.get("last_evaluated_at_utc")
        snap = snaps.get(sym) or {}
        tip = snap.get("tip_bar") or status.get("tip_bar")
        risk = book.get("risk_percent")
        risk_label = None
        if isinstance(risk, (int, float)):
            risk_label = f"{float(risk) * 100:.1f}%"
        rows.append(
            {
                "symbol": sym,
                "tier": str(book.get("tier") or status.get("tier") or "").upper()
                or None,
                "risk_percent": risk,
                "risk_label": risk_label,
                "last_closed_1h_bar": tip,
                "trend_1h": status.get("trend_1h"),
                "trend_4h": status.get("trend_4h"),
                "htf_alignment": status.get("htf_alignment"),
                "bos_status": status.get("bos_status"),
                "watcher_status": status.get("label"),
                "watcher_status_code": status.get("status"),
                "open_trade_id": status.get("open_trade_id"),
                "paper_label": (
                    f"V1 paper trade open — trade_id {status.get('open_trade_id')}"
                    if status.get("open_trade_id")
                    else "no open v1 position"
                ),
                "last_evaluated_at_utc": last_eval,
                "timeframe": "1h",
                "path": "A",
                "combo_id": getattr(watcher, "books", None) and "COMBO_02" or "COMBO_02",
                "read_only": True,
                "creates_orders": False,
            }
        )
    return rows


def utc_now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()
